// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: getstations.proto

package getstations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStationsRequest) Reset() {
	*x = GetStationsRequest{}
	mi := &file_getstations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStationsRequest) ProtoMessage() {}

func (x *GetStationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_getstations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStationsRequest.ProtoReflect.Descriptor instead.
func (*GetStationsRequest) Descriptor() ([]byte, []int) {
	return file_getstations_proto_rawDescGZIP(), []int{0}
}

func (x *GetStationsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Station struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ListenUrl     string                 `protobuf:"bytes,4,opt,name=listen_url,json=listenUrl,proto3" json:"listen_url,omitempty"`
	IsPublic      bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Cover         string                 `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Station) Reset() {
	*x = Station{}
	mi := &file_getstations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Station) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Station) ProtoMessage() {}

func (x *Station) ProtoReflect() protoreflect.Message {
	mi := &file_getstations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Station.ProtoReflect.Descriptor instead.
func (*Station) Descriptor() ([]byte, []int) {
	return file_getstations_proto_rawDescGZIP(), []int{1}
}

func (x *Station) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Station) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Station) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Station) GetListenUrl() string {
	if x != nil {
		return x.ListenUrl
	}
	return ""
}

func (x *Station) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Station) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

type GetStationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Stations      []*Station             `protobuf:"bytes,2,rep,name=stations,proto3" json:"stations,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStationsResponse) Reset() {
	*x = GetStationsResponse{}
	mi := &file_getstations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStationsResponse) ProtoMessage() {}

func (x *GetStationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_getstations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStationsResponse.ProtoReflect.Descriptor instead.
func (*GetStationsResponse) Descriptor() ([]byte, []int) {
	return file_getstations_proto_rawDescGZIP(), []int{2}
}

func (x *GetStationsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetStationsResponse) GetStations() []*Station {
	if x != nil {
		return x.Stations
	}
	return nil
}

func (x *GetStationsResponse) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

var File_getstations_proto protoreflect.FileDescriptor

const file_getstations_proto_rawDesc = "" +
	"\n" +
	"\x11getstations.proto\"*\n" +
	"\x12getStationsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xa1\x01\n" +
	"\aStation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"listen_url\x18\x04 \x01(\tR\tlistenUrl\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\x12\x14\n" +
	"\x05cover\x18\x06 \x01(\tR\x05cover\"m\n" +
	"\x13GetStationsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12$\n" +
	"\bstations\x18\x02 \x03(\v2\b.StationR\bstations\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile2G\n" +
	"\vGetStations\x128\n" +
	"\vGetStations\x12\x13.getStationsRequest\x1a\x14.GetStationsResponseB0Z.github.com/Yarandi/radio_player_go/getstationsb\x06proto3"

var (
	file_getstations_proto_rawDescOnce sync.Once
	file_getstations_proto_rawDescData []byte
)

func file_getstations_proto_rawDescGZIP() []byte {
	file_getstations_proto_rawDescOnce.Do(func() {
		file_getstations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_getstations_proto_rawDesc), len(file_getstations_proto_rawDesc)))
	})
	return file_getstations_proto_rawDescData
}

var file_getstations_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_getstations_proto_goTypes = []any{
	(*GetStationsRequest)(nil),  // 0: getStationsRequest
	(*Station)(nil),             // 1: Station
	(*GetStationsResponse)(nil), // 2: GetStationsResponse
}
var file_getstations_proto_depIdxs = []int32{
	1, // 0: GetStationsResponse.stations:type_name -> Station
	0, // 1: GetStations.GetStations:input_type -> getStationsRequest
	2, // 2: GetStations.GetStations:output_type -> GetStationsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_getstations_proto_init() }
func file_getstations_proto_init() {
	if File_getstations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_getstations_proto_rawDesc), len(file_getstations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getstations_proto_goTypes,
		DependencyIndexes: file_getstations_proto_depIdxs,
		MessageInfos:      file_getstations_proto_msgTypes,
	}.Build()
	File_getstations_proto = out.File
	file_getstations_proto_goTypes = nil
	file_getstations_proto_depIdxs = nil
}
