// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: getstations.proto

package getstations

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetStations_GetStations_FullMethodName = "/GetStations/GetStations"
)

// GetStationsClient is the client API for GetStations service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetStationsClient interface {
	GetStations(ctx context.Context, in *GetStationsRequest, opts ...grpc.CallOption) (*GetStationsResponse, error)
}

type getStationsClient struct {
	cc grpc.ClientConnInterface
}

func NewGetStationsClient(cc grpc.ClientConnInterface) GetStationsClient {
	return &getStationsClient{cc}
}

func (c *getStationsClient) GetStations(ctx context.Context, in *GetStationsRequest, opts ...grpc.CallOption) (*GetStationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStationsResponse)
	err := c.cc.Invoke(ctx, GetStations_GetStations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetStationsServer is the server API for GetStations service.
// All implementations must embed UnimplementedGetStationsServer
// for forward compatibility.
type GetStationsServer interface {
	GetStations(context.Context, *GetStationsRequest) (*GetStationsResponse, error)
	mustEmbedUnimplementedGetStationsServer()
}

// UnimplementedGetStationsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetStationsServer struct{}

func (UnimplementedGetStationsServer) GetStations(context.Context, *GetStationsRequest) (*GetStationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStations not implemented")
}
func (UnimplementedGetStationsServer) mustEmbedUnimplementedGetStationsServer() {}
func (UnimplementedGetStationsServer) testEmbeddedByValue()                     {}

// UnsafeGetStationsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetStationsServer will
// result in compilation errors.
type UnsafeGetStationsServer interface {
	mustEmbedUnimplementedGetStationsServer()
}

func RegisterGetStationsServer(s grpc.ServiceRegistrar, srv GetStationsServer) {
	// If the following call pancis, it indicates UnimplementedGetStationsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetStations_ServiceDesc, srv)
}

func _GetStations_GetStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetStationsServer).GetStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetStations_GetStations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetStationsServer).GetStations(ctx, req.(*GetStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetStations_ServiceDesc is the grpc.ServiceDesc for GetStations service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetStations_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GetStations",
	HandlerType: (*GetStationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStations",
			Handler:    _GetStations_GetStations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "getstations.proto",
}
