// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: profileupdater.proto

package profileupdater

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileUpdaterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Mobile          string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Token           string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	FirstName       string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName        string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Password        string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,7,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProfileUpdaterRequest) Reset() {
	*x = ProfileUpdaterRequest{}
	mi := &file_profileupdater_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileUpdaterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUpdaterRequest) ProtoMessage() {}

func (x *ProfileUpdaterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profileupdater_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUpdaterRequest.ProtoReflect.Descriptor instead.
func (*ProfileUpdaterRequest) Descriptor() ([]byte, []int) {
	return file_profileupdater_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileUpdaterRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ProfileUpdaterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ProfileUpdaterRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ProfileUpdaterRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ProfileUpdaterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ProfileUpdaterRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type ProfileUpdaterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileUpdaterResponse) Reset() {
	*x = ProfileUpdaterResponse{}
	mi := &file_profileupdater_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileUpdaterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUpdaterResponse) ProtoMessage() {}

func (x *ProfileUpdaterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profileupdater_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUpdaterResponse.ProtoReflect.Descriptor instead.
func (*ProfileUpdaterResponse) Descriptor() ([]byte, []int) {
	return file_profileupdater_proto_rawDescGZIP(), []int{1}
}

func (x *ProfileUpdaterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProfileUpdaterResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProfileUpdaterResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ProfileUpdaterResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ProfileUpdaterResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ProfileUpdaterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_profileupdater_proto protoreflect.FileDescriptor

const file_profileupdater_proto_rawDesc = "" +
	"\n" +
	"\x14profileupdater.proto\"\xc8\x01\n" +
	"\x15ProfileUpdaterRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12)\n" +
	"\x10confirm_password\x18\a \x01(\tR\x0fconfirmPassword\"\xbb\x01\n" +
	"\x16ProfileUpdaterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage2S\n" +
	"\x0eProfileUpdater\x12A\n" +
	"\x0eProfileUpdater\x12\x16.ProfileUpdaterRequest\x1a\x17.ProfileUpdaterResponseB3Z1github.com/Yarandi/radio_player_go/profileupdaterb\x06proto3"

var (
	file_profileupdater_proto_rawDescOnce sync.Once
	file_profileupdater_proto_rawDescData []byte
)

func file_profileupdater_proto_rawDescGZIP() []byte {
	file_profileupdater_proto_rawDescOnce.Do(func() {
		file_profileupdater_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profileupdater_proto_rawDesc), len(file_profileupdater_proto_rawDesc)))
	})
	return file_profileupdater_proto_rawDescData
}

var file_profileupdater_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_profileupdater_proto_goTypes = []any{
	(*ProfileUpdaterRequest)(nil),  // 0: ProfileUpdaterRequest
	(*ProfileUpdaterResponse)(nil), // 1: ProfileUpdaterResponse
}
var file_profileupdater_proto_depIdxs = []int32{
	0, // 0: ProfileUpdater.ProfileUpdater:input_type -> ProfileUpdaterRequest
	1, // 1: ProfileUpdater.ProfileUpdater:output_type -> ProfileUpdaterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_profileupdater_proto_init() }
func file_profileupdater_proto_init() {
	if File_profileupdater_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profileupdater_proto_rawDesc), len(file_profileupdater_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profileupdater_proto_goTypes,
		DependencyIndexes: file_profileupdater_proto_depIdxs,
		MessageInfos:      file_profileupdater_proto_msgTypes,
	}.Build()
	File_profileupdater_proto = out.File
	file_profileupdater_proto_goTypes = nil
	file_profileupdater_proto_depIdxs = nil
}
