// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: donation.proto

package donationfields

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DonationConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DonationConfigRequest) Reset() {
	*x = DonationConfigRequest{}
	mi := &file_donation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DonationConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonationConfigRequest) ProtoMessage() {}

func (x *DonationConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_donation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonationConfigRequest.ProtoReflect.Descriptor instead.
func (*DonationConfigRequest) Descriptor() ([]byte, []int) {
	return file_donation_proto_rawDescGZIP(), []int{0}
}

func (x *DonationConfigRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type DonationConfigResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DonationToken      string                 `protobuf:"bytes,2,opt,name=donation_token,json=donationToken,proto3" json:"donation_token,omitempty"`
	DonationGoalAmount string                 `protobuf:"bytes,3,opt,name=donation_goal_amount,json=donationGoalAmount,proto3" json:"donation_goal_amount,omitempty"`
	UserDonationUrl    string                 `protobuf:"bytes,4,opt,name=user_donation_url,json=userDonationUrl,proto3" json:"user_donation_url,omitempty"`
	RecentDonationsUrl string                 `protobuf:"bytes,5,opt,name=recent_donations_url,json=recentDonationsUrl,proto3" json:"recent_donations_url,omitempty"`
	Message            string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DonationConfigResponse) Reset() {
	*x = DonationConfigResponse{}
	mi := &file_donation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DonationConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonationConfigResponse) ProtoMessage() {}

func (x *DonationConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_donation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonationConfigResponse.ProtoReflect.Descriptor instead.
func (*DonationConfigResponse) Descriptor() ([]byte, []int) {
	return file_donation_proto_rawDescGZIP(), []int{1}
}

func (x *DonationConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DonationConfigResponse) GetDonationToken() string {
	if x != nil {
		return x.DonationToken
	}
	return ""
}

func (x *DonationConfigResponse) GetDonationGoalAmount() string {
	if x != nil {
		return x.DonationGoalAmount
	}
	return ""
}

func (x *DonationConfigResponse) GetUserDonationUrl() string {
	if x != nil {
		return x.UserDonationUrl
	}
	return ""
}

func (x *DonationConfigResponse) GetRecentDonationsUrl() string {
	if x != nil {
		return x.RecentDonationsUrl
	}
	return ""
}

func (x *DonationConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_donation_proto protoreflect.FileDescriptor

const file_donation_proto_rawDesc = "" +
	"\n" +
	"\x0edonation.proto\"+\n" +
	"\x15DonationConfigRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x83\x02\n" +
	"\x16DonationConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0edonation_token\x18\x02 \x01(\tR\rdonationToken\x120\n" +
	"\x14donation_goal_amount\x18\x03 \x01(\tR\x12donationGoalAmount\x12*\n" +
	"\x11user_donation_url\x18\x04 \x01(\tR\x0fuserDonationUrl\x120\n" +
	"\x14recent_donations_url\x18\x05 \x01(\tR\x12recentDonationsUrl\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage2V\n" +
	"\x0eDonationConfig\x12D\n" +
	"\x11GetDonationConfig\x12\x16.DonationConfigRequest\x1a\x17.DonationConfigResponseB3Z1github.com/Yarandi/radio_player_go/donationfieldsb\x06proto3"

var (
	file_donation_proto_rawDescOnce sync.Once
	file_donation_proto_rawDescData []byte
)

func file_donation_proto_rawDescGZIP() []byte {
	file_donation_proto_rawDescOnce.Do(func() {
		file_donation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_donation_proto_rawDesc), len(file_donation_proto_rawDesc)))
	})
	return file_donation_proto_rawDescData
}

var file_donation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_donation_proto_goTypes = []any{
	(*DonationConfigRequest)(nil),  // 0: DonationConfigRequest
	(*DonationConfigResponse)(nil), // 1: DonationConfigResponse
}
var file_donation_proto_depIdxs = []int32{
	0, // 0: DonationConfig.GetDonationConfig:input_type -> DonationConfigRequest
	1, // 1: DonationConfig.GetDonationConfig:output_type -> DonationConfigResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_donation_proto_init() }
func file_donation_proto_init() {
	if File_donation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_donation_proto_rawDesc), len(file_donation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_donation_proto_goTypes,
		DependencyIndexes: file_donation_proto_depIdxs,
		MessageInfos:      file_donation_proto_msgTypes,
	}.Build()
	File_donation_proto = out.File
	file_donation_proto_goTypes = nil
	file_donation_proto_depIdxs = nil
}
