// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1-devel
// 	protoc        v5.26.1
// source: getotp.proto

package getotp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOTPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
}

func (x *GetOTPRequest) Reset() {
	*x = GetOTPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getotp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOTPRequest) ProtoMessage() {}

func (x *GetOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_getotp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOTPRequest.ProtoReflect.Descriptor instead.
func (*GetOTPRequest) Descriptor() ([]byte, []int) {
	return file_getotp_proto_rawDescGZIP(), []int{0}
}

func (x *GetOTPRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type GetOTPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Mobile  string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Otp     string `protobuf:"bytes,3,opt,name=otp,proto3" json:"otp,omitempty"`
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetOTPResponse) Reset() {
	*x = GetOTPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getotp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOTPResponse) ProtoMessage() {}

func (x *GetOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_getotp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOTPResponse.ProtoReflect.Descriptor instead.
func (*GetOTPResponse) Descriptor() ([]byte, []int) {
	return file_getotp_proto_rawDescGZIP(), []int{1}
}

func (x *GetOTPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetOTPResponse) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *GetOTPResponse) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

func (x *GetOTPResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_getotp_proto protoreflect.FileDescriptor

var file_getotp_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x65, 0x74, 0x6f, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x22, 0x6e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4f, 0x54,
	0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f,
	0x74, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x74, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x33, 0x0a, 0x06, 0x67, 0x65, 0x74, 0x6f, 0x74,
	0x70, 0x12, 0x29, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4f, 0x54, 0x50, 0x12, 0x0e, 0x2e, 0x47, 0x65,
	0x74, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x47, 0x65,
	0x74, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x59, 0x61, 0x72, 0x61, 0x6e,
	0x64, 0x69, 0x2f, 0x72, 0x61, 0x64, 0x69, 0x6f, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x67, 0x6f, 0x2f, 0x67, 0x65, 0x74, 0x6f, 0x74, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_getotp_proto_rawDescOnce sync.Once
	file_getotp_proto_rawDescData = file_getotp_proto_rawDesc
)

func file_getotp_proto_rawDescGZIP() []byte {
	file_getotp_proto_rawDescOnce.Do(func() {
		file_getotp_proto_rawDescData = protoimpl.X.CompressGZIP(file_getotp_proto_rawDescData)
	})
	return file_getotp_proto_rawDescData
}

var file_getotp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_getotp_proto_goTypes = []interface{}{
	(*GetOTPRequest)(nil),  // 0: GetOTPRequest
	(*GetOTPResponse)(nil), // 1: GetOTPResponse
}
var file_getotp_proto_depIdxs = []int32{
	0, // 0: getotp.GetOTP:input_type -> GetOTPRequest
	1, // 1: getotp.GetOTP:output_type -> GetOTPResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_getotp_proto_init() }
func file_getotp_proto_init() {
	if File_getotp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_getotp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOTPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getotp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOTPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_getotp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getotp_proto_goTypes,
		DependencyIndexes: file_getotp_proto_depIdxs,
		MessageInfos:      file_getotp_proto_msgTypes,
	}.Build()
	File_getotp_proto = out.File
	file_getotp_proto_rawDesc = nil
	file_getotp_proto_goTypes = nil
	file_getotp_proto_depIdxs = nil
}
