// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: signupper.proto

package signupper

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Signupper_Signup_FullMethodName = "/Signupper/Signup"
)

// SignupperClient is the client API for Signupper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignupperClient interface {
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
}

type signupperClient struct {
	cc grpc.ClientConnInterface
}

func NewSignupperClient(cc grpc.ClientConnInterface) SignupperClient {
	return &signupperClient{cc}
}

func (c *signupperClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, Signupper_Signup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignupperServer is the server API for Signupper service.
// All implementations must embed UnimplementedSignupperServer
// for forward compatibility.
type SignupperServer interface {
	Signup(context.Context, *SignupRequest) (*SignupResponse, error)
	mustEmbedUnimplementedSignupperServer()
}

// UnimplementedSignupperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignupperServer struct{}

func (UnimplementedSignupperServer) Signup(context.Context, *SignupRequest) (*SignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedSignupperServer) mustEmbedUnimplementedSignupperServer() {}
func (UnimplementedSignupperServer) testEmbeddedByValue()                   {}

// UnsafeSignupperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignupperServer will
// result in compilation errors.
type UnsafeSignupperServer interface {
	mustEmbedUnimplementedSignupperServer()
}

func RegisterSignupperServer(s grpc.ServiceRegistrar, srv SignupperServer) {
	// If the following call pancis, it indicates UnimplementedSignupperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Signupper_ServiceDesc, srv)
}

func _Signupper_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignupperServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signupper_Signup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignupperServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Signupper_ServiceDesc is the grpc.ServiceDesc for Signupper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Signupper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Signupper",
	HandlerType: (*SignupperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _Signupper_Signup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signupper.proto",
}
