// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: signupper.proto

package signupper

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SignupperClient is the client API for Signupper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignupperClient interface {
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
}

type signupperClient struct {
	cc grpc.ClientConnInterface
}

func NewSignupperClient(cc grpc.ClientConnInterface) SignupperClient {
	return &signupperClient{cc}
}

func (c *signupperClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, "/Signupper/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignupperServer is the server API for Signupper service.
// All implementations must embed UnimplementedSignupperServer
// for forward compatibility
type SignupperServer interface {
	Signup(context.Context, *SignupRequest) (*SignupResponse, error)
	mustEmbedUnimplementedSignupperServer()
}

// UnimplementedSignupperServer must be embedded to have forward compatible implementations.
type UnimplementedSignupperServer struct {
}

func (UnimplementedSignupperServer) Signup(context.Context, *SignupRequest) (*SignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedSignupperServer) mustEmbedUnimplementedSignupperServer() {}

// UnsafeSignupperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignupperServer will
// result in compilation errors.
type UnsafeSignupperServer interface {
	mustEmbedUnimplementedSignupperServer()
}

func RegisterSignupperServer(s grpc.ServiceRegistrar, srv SignupperServer) {
	s.RegisterService(&Signupper_ServiceDesc, srv)
}

func _Signupper_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignupperServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Signupper/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignupperServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Signupper_ServiceDesc is the grpc.ServiceDesc for Signupper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Signupper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Signupper",
	HandlerType: (*SignupperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _Signupper_Signup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signupper.proto",
}
