// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: signupper.proto

package signupper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Otpcode       string                 `protobuf:"bytes,2,opt,name=otpcode,proto3" json:"otpcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_signupper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signupper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_signupper_proto_rawDescGZIP(), []int{0}
}

func (x *SignupRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *SignupRequest) GetOtpcode() string {
	if x != nil {
		return x.Otpcode
	}
	return ""
}

type SignupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupResponse) Reset() {
	*x = SignupResponse{}
	mi := &file_signupper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupResponse) ProtoMessage() {}

func (x *SignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signupper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupResponse.ProtoReflect.Descriptor instead.
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return file_signupper_proto_rawDescGZIP(), []int{1}
}

func (x *SignupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignupResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SignupResponse) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *SignupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_signupper_proto protoreflect.FileDescriptor

const file_signupper_proto_rawDesc = "" +
	"\n" +
	"\x0fsignupper.proto\"A\n" +
	"\rSignupRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x18\n" +
	"\aotpcode\x18\x02 \x01(\tR\aotpcode\"r\n" +
	"\x0eSignupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage26\n" +
	"\tSignupper\x12)\n" +
	"\x06Signup\x12\x0e.SignupRequest\x1a\x0f.SignupResponseB.Z,github.com/Yarandi/radio_player_go/signupperb\x06proto3"

var (
	file_signupper_proto_rawDescOnce sync.Once
	file_signupper_proto_rawDescData []byte
)

func file_signupper_proto_rawDescGZIP() []byte {
	file_signupper_proto_rawDescOnce.Do(func() {
		file_signupper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signupper_proto_rawDesc), len(file_signupper_proto_rawDesc)))
	})
	return file_signupper_proto_rawDescData
}

var file_signupper_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_signupper_proto_goTypes = []any{
	(*SignupRequest)(nil),  // 0: SignupRequest
	(*SignupResponse)(nil), // 1: SignupResponse
}
var file_signupper_proto_depIdxs = []int32{
	0, // 0: Signupper.Signup:input_type -> SignupRequest
	1, // 1: Signupper.Signup:output_type -> SignupResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_signupper_proto_init() }
func file_signupper_proto_init() {
	if File_signupper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signupper_proto_rawDesc), len(file_signupper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signupper_proto_goTypes,
		DependencyIndexes: file_signupper_proto_depIdxs,
		MessageInfos:      file_signupper_proto_msgTypes,
	}.Build()
	File_signupper_proto = out.File
	file_signupper_proto_goTypes = nil
	file_signupper_proto_depIdxs = nil
}
