// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: logouter.proto

package logouter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogouterClient is the client API for Logouter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogouterClient interface {
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
}

type logouterClient struct {
	cc grpc.ClientConnInterface
}

func NewLogouterClient(cc grpc.ClientConnInterface) LogouterClient {
	return &logouterClient{cc}
}

func (c *logouterClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/Logouter/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogouterServer is the server API for Logouter service.
// All implementations must embed UnimplementedLogouterServer
// for forward compatibility
type LogouterServer interface {
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	mustEmbedUnimplementedLogouterServer()
}

// UnimplementedLogouterServer must be embedded to have forward compatible implementations.
type UnimplementedLogouterServer struct {
}

func (UnimplementedLogouterServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedLogouterServer) mustEmbedUnimplementedLogouterServer() {}

// UnsafeLogouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogouterServer will
// result in compilation errors.
type UnsafeLogouterServer interface {
	mustEmbedUnimplementedLogouterServer()
}

func RegisterLogouterServer(s grpc.ServiceRegistrar, srv LogouterServer) {
	s.RegisterService(&Logouter_ServiceDesc, srv)
}

func _Logouter_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogouterServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Logouter/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogouterServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Logouter_ServiceDesc is the grpc.ServiceDesc for Logouter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Logouter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Logouter",
	HandlerType: (*LogouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Logout",
			Handler:    _Logouter_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logouter.proto",
}
